# Generated by Django 5.1.2 on 2026-05-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
