# Generated by Django 5.1.2 on 2026-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchase_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (USD)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (UZS)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (eski)'),
        ),
    ]
