# Generated by Django 5.2.15 on 2026-06-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
        ('purchases', '0003_purchase_total_usd_purchase_total_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.productvariant', verbose_name='Variant'),
        ),
    ]
