# Generated by Django 5.1.2 on 2026-05-29 12:00

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism familiya')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarz')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami xarid')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('vip', 'VIP'), ('debtor', 'Qarzdor'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Status')),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram chat ID')),
                ('link_token', models.CharField(default=apps.customers.models._generate_link_token, help_text='Bot deep link: https://t.me/<bot>?start=cust_<token>', max_length=32, unique=True, verbose_name='Deep link token')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Xabarlar yoqilgan')),
                ('last_debt_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi qarz eslatma vaqti')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
