# Generated by Django 5.1.2 on 2026-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_spent',
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarz (USD)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarz (UZS)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami xarid (USD)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami xarid (UZS)'),
        ),
    ]
