# Generated by Django 5.2.15 on 2026-06-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Variant nomi')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Shtrix kod')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='0 — mahsulot narxidan olinadi', max_digits=12, verbose_name='Sotib olish narxi')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='0 — mahsulot narxidan olinadi', max_digits=12, verbose_name='Sotish narxi')),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['name'],
            },
        ),
    ]
