# Generated by Django 5.2.15 on 2026-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, verbose_name='Kam qolish chegarasi'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kg'), ('litr', 'Litr'), ('metr', 'Metr')], default='dona', max_length=10, verbose_name='Birlik'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sotish narxi'),
        ),
    ]
