# Generated by Django 5.1.2 on 2026-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='debt_due_date',
            field=models.DateField(blank=True, help_text="Faqat nasiya sotuvlar uchun: to'lov muddati", null=True, verbose_name='Nasiya muddati'),
        ),
    ]
