# Generated by Django 5.1.2 on 2026-05-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=3, verbose_name='Valyuta'),
        ),
    ]
