# Generated by Django 5.1.2 on 2026-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nasiya sotuvda mijoz to'lagan miqdor", max_digits=14, verbose_name="To'langan summa"),
        ),
    ]
