# Generated by Django 5.1.2 on 2026-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='currency',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (USD)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (UZS)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami (UZS, eski)'),
        ),
    ]
