# Generated by Django 5.2.15 on 2026-06-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
        ('sales', '0007_sale_debt_due_reminder_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.productvariant', verbose_name='Variant'),
        ),
    ]
